/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as GenerationsRouteImport } from './routes/generations'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as UniversitiesSlugRouteImport } from './routes/universities.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationsRoute = GenerationsRouteImport.update({
  id: '/generations',
  path: '/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/universities/',
  path: '/universities/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesSlugRoute = UniversitiesSlugRouteImport.update({
  id: '/universities/$slug',
  path: '/universities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/generations': typeof GenerationsRoute
  '/programs': typeof ProgramsRoute
  '/regions': typeof RegionsRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/universities/': typeof UniversitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/generations': typeof GenerationsRoute
  '/programs': typeof ProgramsRoute
  '/regions': typeof RegionsRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/universities': typeof UniversitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/generations': typeof GenerationsRoute
  '/programs': typeof ProgramsRoute
  '/regions': typeof RegionsRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/universities/': typeof UniversitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/generations'
    | '/programs'
    | '/regions'
    | '/universities/$slug'
    | '/universities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/generations'
    | '/programs'
    | '/regions'
    | '/universities/$slug'
    | '/universities'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/generations'
    | '/programs'
    | '/regions'
    | '/universities/$slug'
    | '/universities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  GenerationsRoute: typeof GenerationsRoute
  ProgramsRoute: typeof ProgramsRoute
  RegionsRoute: typeof RegionsRoute
  UniversitiesSlugRoute: typeof UniversitiesSlugRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generations': {
      id: '/generations'
      path: '/generations'
      fullPath: '/generations'
      preLoaderRoute: typeof GenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/universities'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$slug': {
      id: '/universities/$slug'
      path: '/universities/$slug'
      fullPath: '/universities/$slug'
      preLoaderRoute: typeof UniversitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  GenerationsRoute: GenerationsRoute,
  ProgramsRoute: ProgramsRoute,
  RegionsRoute: RegionsRoute,
  UniversitiesSlugRoute: UniversitiesSlugRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
